fixed usage / help

diff --git a/zfs-sync b/zfs-sync
--- a/zfs-sync
+++ b/zfs-sync
@@ -1,24 +1,23 @@
 #!/usr/bin/env bash
-# BASH3 Boilerplate
 #
-# This file:
-#  - Is a template to write better bash scripts
-#  - Is delete-key friendly, in case you don't need e.g. command line option parsing
-#
-# More info:
+# Thanks to:
 #  - https://github.com/kvz/bash3boilerplate
-#  - http://kvz.io/blog/2013/02/26/introducing-bash3boilerplate/
+#  - http://www.funtoo.org/Keychain
 #
-# Version 1.1.0
+# Version 0.0.1
 #
 # Authors:
 #  - Travis Osterman (travis@osterman.co)
 #
 # Usage:
-#  LOG_LEVEL=7 ./main.sh -f /tmp/x -d
+#  LOG_LEVEL=6 zfs-sync "tank/home" "backup@server2.tld.com" "tank/backup/server1.tld.com"
 #
-# Licensed under MIT
+# License
 #   TBD
+
+ZFS_SYNC_HOME="/root/.zfs-sync"
+
+
 ### Source file for auth
 #####################################################################
 # TODO ... only if keyring is installed and directories exist
@@ -46,8 +45,12 @@ EOF
 # Set magic variables for current file and its directory. 
 # BASH_SOURCE[0] is used so we can display the current file even if it is sourced by a parent script.
 # If you need the script that was executed, consider using $0 instead.
+# Set magic variables for current file & dir
 __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 __file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
+__root="$(cd "$(dirname "${__dir}")" && pwd)" # <-- change this
+__base="$(basename ${__file} .sh)"
+
 
 
 ### Functions
@@ -79,11 +82,13 @@ function info ()      { [ "${LOG_LEVEL}" -ge 6 ] && echo "$(_fmt info) ${@}" 1>&
 function debug ()     { [ "${LOG_LEVEL}" -ge 7 ] && echo "$(_fmt debug) ${@}" 1>&2 || true; }
 
 function help () {
-  echo "" 1>&2
-  echo " ${@}" 1>&2
-  echo "" 1>&2
-  echo "  ${usage}" 1>&2
-  echo "" 1>&2
+  set +o xtrace
+  echo -e "${__base}: snapshot and send a zfs filesystem to another host"
+  echo -e "Usage:"
+  echo -e "\t${__base}: [options] local-filesystem remote-server remote-filesystem"
+  echo -e "Options: -[vdfFhies]"
+  echo -e "\t[ --verbose           ] [ --debug]            [ --help]"
+  echo -e "\t[ --ssh-opts <string> ] [ --email <address> ]"
   exit 1
 }
 
@@ -96,7 +101,7 @@ trap cleanup_before_exit EXIT
 ### Parse commandline options
 #####################################################################
 
-TEMP=`getopt -o vdfFhies: --long verbose,debug,full,fallback,help,incremental,email,ssh-opts: \
+TEMP=`getopt -o vdhse: --long verbose,debug,full,fallback,help,incremental,email,ssh-opts: \
              -n "${__base}" -- "$@"`
 
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
@@ -116,11 +121,8 @@ while true; do
   case "$1" in
     -v | --verbose ) VERBOSE=true; shift ;;
     -d | --debug ) DEBUG=true; shift ;;
-    -f | --full ) FULL=true; shift ;;
-    -F | --fallback ) FALLBACK=true; shift ;;
     -h | --help ) HELP=true; shift ;;
-    -i | --incremental ) INCREMENTAL=true; shift ;;
-    -m | --ssh-opts ) SSH_OPTS="$2"; shift 2 ;;
+    -s | --ssh-opts ) SSH_OPTS="$2"; shift 2 ;;
     -e | --email ) EMAIL="$2"; shift 2 ;;
     -- ) shift; break ;;
     * ) break ;;
@@ -131,6 +133,12 @@ done
 set -o errexit  # error on exit
 set -o nounset  # no undeclared variables
 set -o pipefail # catch errors even when piped
+
+# if help
+if [ "${HELP}" = true ]
+  then
+  help
+fi
 
 # check argument param count
 if [ $# -lt 3 ]
@@ -206,9 +214,8 @@ LOCAL_FS_NAME=$(echo "$LOCAL_FS" | sed 's:/:-:g')
 REMOTE_FS_NAME=$(echo "$REMOTE_FS" | sed 's:/:-:g')
 
 # set zfs-sync home and ensure it exists
-ZFS_SYNC_HOME="${HOME}/.zfs-sync"
 if [ ! -d "${ZFS_SYNC_HOME}" ]; then
-  mkdir "${ZFS_SYNC_HOME}"
+  mkdir "${ZFS_SYNC_HOME}" || error "cannot mkdir ${ZFS_SYNC_HOME}"; exit 1
 fi
 
 # ensure that a sync file exists
